base/urls.py
from django.urls import path 
from . import views

app_name = 'base'
urlpatterns = [
    path('login', views.loginAction, name="login"),
    path('register', views.registerAction, name="register"),

    path('', views.home, name="home"),
    path('rooms/<int:id>', views.room, name="room"),
    path('rooms/create', views.createRoom, name="create.room"),
    path('rooms/store', views.storeRoom, name="store.room"),
    path('rooms/edit/<int:id>', views.editRoom, name="edit.room"),
    path('rooms/update/<int:id>', views.updateRoom, name="update.room"),
    path('rooms/delete/<int:id>', views.destroyRoom, name="destroy.room"),
]

messageApp/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('base.urls')),
    path('admin/', admin.site.urls),
]

base/models.py
from django.db import models
from django.contrib.auth.models import User

class Topic(models.Model):
    name = models.CharField(max_length=200)
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add =True)

    def __str__(self):
        return self.name

class Room(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    topic = models.ForeignKey(Topic, on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add =True)

    class Meta:
        ordering = [ '-updated_at', '-created_at']

    def __str__(self):
        return self.name

class Message(models.Model):
    User = models.ForeignKey(User, on_delete=models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    body = models.TextField()
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add =True)

    def __str__(self):
        return self.body

base/forms.py
from django.forms import ModelForm
from .models import Room

class RoomForm(ModelForm):
    class Meta:
        model = Room
        fields = '__all__'

base/views.py
from email.mime import message
from django.shortcuts import render, redirect
from django.db.models import Q
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm
from django.http import HttpResponse
from django.contrib import messages
from .models import Room
from .forms import RoomForm

# Create your views here.

# def showLoginForm(request):
#     return render(request, 'auth/login.html')

def loginAction(request):
    if request.method == 'POST' :
        username = request.POST.get('username')
        password = request.POST.get('password')
        try:
            user = User.objects.get(username=username)
        except:
            messages.error(request, 'User does not exist')
        
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('base:home')
        else: 
            messages.error(request, 'Invalid user credentials')
    return render(request, 'auth/login.html')

def registerAction(request):
    if request.method == 'POST' :
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.save()
            return redirect('base:home')
        else:
            messages.error(request, 'An error occurred')
    compact = {
        'form': UserCreationForm()
    }
    return render(request, 'auth/register.html', compact)

def home(request):
    rooms = Room.objects.all()
    compact = {
        'rooms': rooms
    }
    return render(request, 'home/index.html' , compact)

def room(request, id):
    room = Room.objects.get(id=id);
    compact = {
        'room': room
    }
    return render(request, 'rooms/show.html' , compact)

def createRoom(request):
    compact = {
        'form': RoomForm
    }
    return render(request, 'rooms/create.html', compact)

def storeRoom(request):
    if request.method == 'POST':
        form = RoomForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('base:home')

def editRoom(request, id):
    room = Room.objects.get(id=id)
    compact = {
        'room': room,
        'form': RoomForm(instance=room)
    }
    return render(request, 'rooms/edit.html', compact)

def updateRoom(request, id):
    room = Room.objects.get(id=id)
    if request.method == 'POST':
        form = RoomForm(request.POST, instance=room)
        if form.is_valid():
            form.save()
            return redirect('base:home')


def destroyRoom(request, id):
    room = Room.objects.get(id=id)
    if request.method == 'POST':
        room.delete()
        return redirect('base:home')
    compact = {
        'obj': room.name
    }
    return render(request, 'defaults/delete.html', compact)

base/templates/defaults/delete.html
{% extends 'base.html' %}
{% block title %} Add Room  {% endblock %}
{% block content %}
    <form action="" method="POST">
        {% csrf_token %}
        <h3> Are you sure you want to delete {{ obj }} ?</h3>
        <a href="{{ request.META.HTTP_REFERER}}"> Go back </a>
        <button type="submit"> Delete Room </button>
    </form>
{% endblock %}  

base/templates/defaults/navigation.html
<nav>
    <h3> Navbar </h3>
    {% if request.user.authenticated %}
        <a href=""> Logout </a>
    {% else %}
        <a href="{% url 'base:login' %}"> Login </a> <br>
    {% endif %}
</nav>

base/templates/home/index.html
{% extends 'base.html' %}
{% block title %} Home page {% endblock %}
{% block content %}
<h3> Home</h3>
<a href="{% url 'base:create.room' %}">Add room</a>
<ul>
    {% for room in rooms %}
    <li>
        <a href="{% url 'base:room' room.id %}">
            {{ room.name }}
        </a> &nbsp;
        <a href="{% url 'base:edit.room' room.id %}"> Edit </a>
        <a href="{% url 'base:destroy.room' room.id %}"> Delete </a>
    </li>
    {% endfor %}
</ul>
{% endblock %}  

base/templates/rooms/create.html
{% extends 'base.html' %}
{% block title %} Add Room  {% endblock %}
{% block content %}
    <form action="{% url 'base:store.room' %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Save</button>
    </form>
{% endblock %}  

base/templates/rooms/edit.html
{% extends 'base.html' %}
{% block title %} Add Room  {% endblock %}
{% block content %}
    <form action="{% url 'base:update.room' room.id %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Save</button>
    </form>
{% endblock %}  

base/templates/rooms/show.html
{% extends 'base.html' %}
{% block title %} Home page {% endblock %}
{% block content %}
    <h3> {{ room.name }} </h3>
    <h3> @{{room.user}} </h3>
    <h3> Topic: {{room.topic.name}} </h3>
{% endblock %}  

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <title> {% block title %}{% endblock %}</title>

    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="robots" content="noindex, nofollow">

    <meta name="google" content="notranslate" />

    <!-- Open Graph Meta -->
    <meta property="og:title" content="">
    <meta property="og:site_name" content="">
    <meta property="og:description" content="">
    <meta property="og:type" content="website">
    <meta property="og:url" content="">
    <meta property="og:image" content="">

    <!-- Icons -->
    <link rel="shortcut icon" href="">
    <link rel="icon" sizes="192x192" type="image/png" href="">
    <link rel="apple-touch-icon" sizes="180x180" href="">

    <!-- Vendor stylesheets -->
    <link rel="stylesheet" href="css/vendors/bootstrap.min.css">
</head>
<body>
    <div class="container">
        {% include 'defaults/navigation.html' %}

        {% block content %}
        {% endblock %}
    </div>
</body>
</html>